### ISSUE TITLE
Problem Being Solved

### ISSUE THREAD

**Issue by guyellis** [nearform/nscale-docs#10]
Create a section in the docs that describes the problem that `nscale` is solving. Give examples of what the current state might be and what it will be after `nscale` is setup and running. Provide an estimate to how long it will take to setup `nscale` to demonstrate the time/value payback.

**Comment by mcdonnelldean** [comment]
I wonder does this tie in with some of the docs @pelger is looking to do for nscale around it's use and business value? @pelger what do you think? If not we can look at putting in a doc for this.

**Comment by pelger** [comment]
Documentation now updated so closing
