### ISSUE TITLE
Fix Documentation Link

### ISSUE THREAD

**Issue by guyellis** [nearform/nscale-docs#11]
The link on http://nscale.nearform.com/ for documentation take you to the deprecated https://github.com/nearform/nscale-workshop destination instead of https://github.com/nearform/nscale-docs

**Comment by darahayes** [comment]
Thanks for spotting this. @pelger @mcollina Can we get this sorted asap? EDIT: If we could get the copyright notice in the footer updated too!

**Comment by darahayes** [comment]
@guyellis I've made a PR to fix the link!

**Comment by mcdonnelldean** [comment]
Merged :D
