### ISSUE TITLE
Boot2Docker FAQs

### ISSUE THREAD

**Issue by mcollina** [nearform/nscale-docs#12]
A lot of people does not put the boot2docker `export ...` commands into their `.bash_profile`. We  need to point out that they need to do it, also in the install instruction.

**Comment by mcdonnelldean** [comment]
@mcollina I checked both docs (quick start & boot2docker install) both have this in them but I would agree with you that this is something that could come up over and over.

Should we begin a common issues FAQ and have this in it? There are other little bits that could go into that doc too, I can get the bones of this done now?

**Comment by mcollina** [comment]
that would be awesome!

**Comment by mcdonnelldean** [comment]
Will do tonight so, I want to add the issues around Sudo too.

**Comment by mcdonnelldean** [comment]
Didn't get to this tonight as I wanted to remove some of the bad info from Glossary and CLI Commands since they are already in the public eye (merge completed). Will do tonight instead.

**Comment by mcdonnelldean** [comment]
This is in the new docs.
